[OCMSversion]
version = "2.0.0 (2017-05-09)"

[logger]
mode = "info"
logFileName = "/var/log/ocms/ocms.log"

[server]
#httpHostIp = "10.194.18.46"  
httpHostPort = 8000
readTimeout = 5000000000 # in nanoseconds
writeTimeout = 10000000000 # in nanoseconds

[chaincode]
chainCodePath     = "github.com/consentv2"
chainCodeVersion  = "v0"
chainCodeID       = "consentv2"
chainID           = "testchannel"
providerName      = "SW"

[path]
repo              = "/var/ocms/fixtures"
statStorePath     = "/var/ocms/fixtures/enroll_user"
networkConfigFile = "/var/ocms/fixtures/config/config_prod.yaml"
channelConfigFile = "/var/ocms/fixtures/channel/testchannel.tx"

[admin]
adminUsername     = "admin"
adminPwd          = "adminpw"